"""add_community_status_to_question_banks

Revision ID: 8928f770c17e
Revises: 5f7148147854
Create Date: 2026-02-15 13:16:48.589639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8928f770c17e'
down_revision: Union[str, Sequence[str], None] = '5f7148147854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.drop_column('community_status')

    # ### end Alembic commands ###
